### ISSUE TITLE
Customer Subscriptions , Invoice and Plan API tests fail since v2.5.0

### ISSUE THREAD

**Issue by hrakotobe** [rebelidealist/stripe-ruby-mock#609]
These groups of tests raise errors on `bundle exec rspec` execution for v2.50 and 2.51:
- Customer Subscriptions 
- Invoice API
- Plan API

### Sample error:
```
  124) StripeMock Server behaves like Customer Subscriptions cancelling a subscription cancels a stripe customer's subscription
     Failure/Error: customer = Stripe::Customer.create(source: gen_card_tk, plan: "the truth")
     NoMethodError:
       undefined method `to_datetime' for 2019-06-21 10:13:57 +0000:Time
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:26
     # (druby://localhost:4999) ./lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb:57:in `get_ending_time'
     # (druby://localhost:4999) ./lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb:18:in `custom_subscription_params'
     # (druby://localhost:4999) ./lib/stripe_mock/request_handlers/customers.rb:43:in `new_customer'
     # (druby://localhost:4999) ./lib/stripe_mock/instance.rb:101:in `mock_request'
     # (druby://localhost:4999) ./lib/stripe_mock/server.rb:21:in `mock_request'
     # ./lib/stripe_mock/client.rb:18:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:103:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:17:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:38:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:32:in `call'
     # ./lib/stripe_mock/api/instance.rb:32:in `block in alias_stripe_method'
     # /usr/local/bundle/gems/stripe-4.19.0/lib/stripe/api_operations/request.rb:19:in `request'
     # /usr/local/bundle/gems/stripe-4.19.0/lib/stripe/api_operations/create.rb:7:in `create'
     # ./spec/shared_stripe_examples/subscription_examples.rb:624:in `block (3 levels) in <top (required)>'
```

## Running environment
I ran the tests with the ruby 2.6.3 official docker images.
These are the `Dockerfile`

### v2.5.0
```
FROM ruby:2.6.3-stretch

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/rebelidealist/stripe-ruby-mock.git stripe-ruby-mock --branch=v2.5.0
WORKDIR  /stripe-ruby-mock
RUN bundle install

CMD bundle exec rspec
```
Full log file of the execution: 
[result_2.5.0.log](https://github.com/rebelidealist/stripe-ruby-mock/files/3314037/result_2.5.0.log)

### v2.5.1
```
FROM ruby:2.6.3-stretch

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/rebelidealist/stripe-ruby-mock.git stripe-ruby-mock --branch=2.5.1
WORKDIR  /stripe-ruby-mock
RUN bundle install

CMD bundle exec rspec
```
Full log file of the execution: 
[result_2.5.1.log](https://github.com/rebelidealist/stripe-ruby-mock/files/3314040/result_2.5.1.log)

Under the same setup, tests are all green for 2.4.1
